{% set version = "4.4.0" %}
{% set name = "tensorflow-datasets" %}

# This is the recipe for tensorflow-datasets
package:
   name: {{ name }}
   version: {{ version }}

source:
  git_url: https://github.com/tensorflow/datasets
  git_rev: v{{ version }}

build:
  number: 1
  string: h{{ PKG_HASH }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
     - python 
  build:
     - git >=2.2 
  run:
   # conda build requirements
     - python 
     - absl-py {{ absl_py }}
     - attrs {{ attrs }} 
     - dill 
     - future
     - numpy {{ numpy }}
     - promise
     - protobuf {{ protobuf }}
     - requests {{ requests }}
     - six {{ six }}
     - tensorflow-metadata
     - termcolor {{ termcolor }}
     - tqdm {{ tqdm }}
     - dataclasses {{ dataclasses }}                    #[py<37]
     - typing_extensions {{ typing_extensions }}        #[py<38]
     - importlib_resources {{ importlib_resources }}    #[py<39]
     - tensorflow-base {{ tensorflow }}

about:
  home: https://github.com/tensorflow/datasets
  license: Apache License 2.0
  license_family: APACHE
  license_file: ../LICENSE
  summary: "A collection of datasets ready to use with TensorFlow"
  description: |
      tensorflow-datasets is a library of public datasets ready to use with
      TensorFlow. Each dataset definition contains the logic necessary to 
      download and prepare the dataset, as well as to read it into a model using the
      `tf.data.Dataset` API.
      Usage outside of TensorFlow is also supported.
  dev_url: https://github.com/tensorflow/datasets.git
  doc_url: https://github.com/tensorflow/datasets.git 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
